apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-api
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-api
  template:
    metadata:
      labels:
        app: agent-api
    spec:
      serviceAccountName: opentelemetrycollector
      containers:
      - name: agent-api
        image: lilusanchez7/agent-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"