apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: monitoring
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:latest  # Light image with curl installed
      command: ["tail", "-f", "/dev/null"]