apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-reloader
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-reloader
  template:
    metadata:
      labels:
        app: config-reloader
    spec:
      serviceAccountName: opentelemetrycollector
      containers:
        - name: config-reloader
          image: config-reloader-image:latest
          imagePullPolicy: Never
          command: ["/bin/bash", "-c"]
          args:
            - |
              while true; do
                sleep 10;
                CURRENT_VERSION="$(kubectl get configmap collector-config -n monitoring -o jsonpath='{.metadata.resourceVersion}')"
                PREVIOUS_VERSION="$(cat /tmp/collector-config-version 2>/dev/null)"

                echo "Current Version: $CURRENT_VERSION, Previous Version: $PREVIOUS_VERSION"

                if [ -z "$PREVIOUS_VERSION" ]; then
                  echo "Storing initial version without sending SIGHUP."
                  echo "$CURRENT_VERSION" > /tmp/collector-config-version
                elif [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
                  echo "Detected change in ConfigMap..."
                  echo "Updating collector config..."
                  echo "$CURRENT_VERSION" > /tmp/collector-config-version

                  echo "Notifying external API to send SIGHUP..."
                  curl -X POST http://host.minikube.internal:8081/reload
                fi
              done
          volumeMounts:
            - mountPath: /tmp
              name: version-storage
      volumes:
        - name: version-storage
          emptyDir: {}