apiVersion: v1
kind: Pod
metadata:
  name: config-checker
  namespace: monitoring
spec:
  containers:
    - name: shell
      image: alpine
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /conf
          name: collector-config
  volumes:
    - name: collector-config
      configMap:
        name: collector-config
