apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 2000000000
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage

    - name: critical alert
      rules:
      - alert: High Node CPU Usage
        expr: avg by (instance) (rate(container_cpu_usage_seconds_total[3m])) > 0.005
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "CPU usage is high in one node"
          description: "CPU usage is above 70% for more than 3 minutes."

      - alert: High Containers CPU Usage
        expr: (sum(rate(container_cpu_usage_seconds_total[2m])) / avg(machine_cpu_cores) * 100) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Containers CPU usage is high"
          description: "The CPU usage across containers is above 80% of the total available CPU cores for more than 1 minute. This could indicate that the containers are consuming excessive CPU resources."

      - alert: High Container Memory Usage
        expr: container_memory_usage_bytes > 500000000
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Memory usage is high"
          description: "Memory usage greater than 1GB for 2 minutes."

  prometheus.yml: |-
    global:
      scrape_interval: 1d
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"