apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-api-chart.fullname" . }}
  namespace: monitoring
  labels:
    {{- include "agent-api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "agent-api-chart.selectorLabels" . | nindent 4 }}
